# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058abf95a905279a16b86789668a123ca2f44f32355bbbec1e08194de85d1ef8d0a6ee946612ca60c72b4657ca98ccaf8f860d41599985fc44ce329bae2adff6

test:
  secret_key_base: f39178677ec6b5c48e83de659e20d56263338dcac094cd63a26febe2a9f2197fc4efff21f9661ee3864b564774b10bdf3e06cd192d7422e65ff693fc15885230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
